apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-backup-minio
  namespace: default
spec:
  instances: 1

  postgresql:
    parameters:
      log_checkpoints: "on"
      log_lock_waits: "on"
      log_min_duration_statement: '1000'
      log_statement: 'ddl'
      log_temp_files: '1024'
      log_autovacuum_min_duration: '1s'
      log_replication_commands: 'on'

  # Example of rolling update strategy:
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover

  # Persistent storage configuration
  storage:
    storageClass: standard
    size: 1Gi
  walStorage:
    storageClass: standard
    size: 1Gi

  bootstrap:
    initdb:
      database: app
      owner: app

  backup:
    target: primary
    barmanObjectStore:
        destinationPath: s3://cnpgpgconf/
        endpointURL: http://minio:9000
        s3Credentials:
          accessKeyId:
            name: backup-storage-creds
            key: ID
          secretAccessKey:
            name: backup-storage-creds
            key: KEY
        wal:
          compression: gzip
        data:
          immediateCheckpoint: true
        tags:
          retention: "30days"
        historyTags:
          retention: "30days"
    retentionPolicy: "30d"